### ISSUE TITLE
1.11.2 - Crash while launching game - Tessellating CCL block in world

### ISSUE THREAD

**Issue by silent-mobious** [TeamMD5/ProjectX#5]
Back again...  It's crashing slightly differently now.  After the client connects to the server, and the screen is initially rendering, the client crashes out to the launcher.  Doesn't play well with CodeChickenLib?  Thanks a lot!

**Mod Versions tested**: NineTailLib-1.11.2-1.6.141-universal.jar, ProjectX-1.11.2-2.1.20-universal.jar, CodeChickenLib-1.11.2-3.0.0.284-universal.jar
**Forge version used**: forge-1.11.2-13.20.1.2421-universal
**Log**: [Pastebin of crash log](https://pastebin.com/gSbDJazu)

Description: Tessellating CCL block in world

java.lang.AbstractMethodError: keri.projectx.client.render.RenderSimpleGlow.renderWorld(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/client/renderer/VertexBuffer;Lnet/minecraft/util/BlockRenderLayer;)Z
	at keri.ninetaillib.lib.render.BlockRenderingAdapter.renderBlock(BlockRenderingAdapter.java:53)
	at codechicken.lib.render.block.BlockRenderingRegistry.renderBlock(BlockRenderingRegistry.java:90)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:52)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:296)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
	at java.lang.Thread.run(Unknown Source)

**Comment by Adam8234** [comment]
ProjectX build 20 only works with NineTailLib build 140 in build 141 we added some stuff to it that broke build 20. Change the version and give an update!

**Comment by silent-mobious** [comment]
![image](https://user-images.githubusercontent.com/12705402/28503869-00bd7092-6fdc-11e7-81ef-7c9d5e10a714.png)

140 seems to be missing...  got another repository somewhere?

**Comment by Adam8234** [comment]
Try 138

**Comment by silent-mobious** [comment]
Ok, looks like 138 works with ProjectX build 20.  Thanks!

**Comment by KitsuneAlex** [comment]
Im sorry for the confusion X.x
